
export interface User {
  id: string;
  name: string;
  email: string;
  photoURL?: string;
  plan: string;
  isLoggedIn: boolean;
  credits: number;
  isAdmin?: boolean;
}

export interface ProcessingState {
  stage: 'idle' | 'analysis' | 'extracting' | 'applying' | 'rendering' | 'validating' | 'completed' | 'failed';
  progress: number;
  message: string;
}

export interface GeneratedAsset {
  id: string;
  url: string;
  type: 'image' | 'video';
  promptData?: any; // Stores the JSON prompt generated by the FashionClone brain
  timestamp: number;
}

export enum GenerationType {
  IMAGE = 'IMAGE',
  VIDEO = 'VIDEO'
}

export enum StylingPreset {
  WEARING = 'wearing',
  HOLDING = 'holding',
  SHOWCASING = 'showcasing',
  FLOATING = 'floating',
  LIFESTYLE = 'lifestyle'
}

export enum ModelTier {
  FLASH = 'gemini-3-flash-preview',
  PRO = 'gemini-3-pro-preview',
  IMAGE_GEN = 'gemini-2.5-flash-image',
  IMAGE_PRO = 'gemini-3-pro-image-preview',
  VIDEO_GEN = 'veo-3.1-fast-generate-preview'
}

// Admin Dashboard Types
export interface UserAccount {
  id: string;
  name: string;
  email: string;
  plan: string;
  status: 'active' | 'suspended' | 'pending';
  joinedDate: string;
  totalGenerations: number;
  credits: number;
}

export interface AdminAnalytics {
  totalUsers: number;
  activeSubscribers: number;
  totalRevenue: number;
  generationsCount: {
    images: number;
    videos: number;
  };
  recentActivity: {
    id: string;
    user: string;
    type: string;
    timestamp: number;
  }[];
}
